apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctionsite-deployment
  labels:
    app: auctionsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctionsite
  template:
    metadata:
      labels:
        app: auctionsite
    spec:
      containers:
      - name: auctionsite
        image: janithadissanayaka/learn:latest
        ports:
        - containerPort: 8080
