apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auctionsite-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: auctionsite.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auctionsite
            port:
              number: 80
